package tools

import (
	"reflect"
	"strings"
	"testing"
)

func TestParseExportStatements(t *testing.T) {
	tests := []struct {
		name     string
		command  string
		expected []string
	}{
		{
			name:     "单个 export",
			command:  "export PATH=/usr/local/go/bin:$PATH",
			expected: []string{"PATH=/usr/local/go/bin:$PATH"},
		},
		{
			name:     "多个 export 在同一行",
			command:  "export A=1 B=2 C=3",
			expected: []string{"A=1", "B=2", "C=3"},
		},
		{
			name:     "多个 export 在不同行",
			command:  "export A=1\nexport B=2",
			expected: []string{"A=1", "B=2"},
		},
		{
			name:     "带双引号的 export",
			command:  `export MY_VAR="hello world"`,
			expected: []string{"MY_VAR=hello world"},
		},
		{
			name:     "带单引号的 export",
			command:  `export MY_VAR='hello world'`,
			expected: []string{"MY_VAR=hello world"},
		},
		{
			name:     "带引号和特殊字符",
			command:  `export PATH="/usr/local/go/bin:$PATH"`,
			expected: []string{"PATH=/usr/local/go/bin:$PATH"},
		},
		{
			name:     "混合引号和无引号",
			command:  `export A=1 B="hello world" C=/path/to/bin`,
			expected: []string{"A=1", "B=hello world", "C=/path/to/bin"},
		},
		{
			name:     "没有 export 命令",
			command:  "echo hello",
			expected: nil,
		},
		{
			name:     "export 后面没有变量",
			command:  "export",
			expected: nil,
		},
		{
			name:     "export 后面是已存在的变量名（无赋值）",
			command:  "export PATH",
			expected: nil,
		},
		{
			name:     "带分号分隔",
			command:  "export A=1; echo done",
			expected: []string{"A=1"},
		},
		{
			name:     "带转义字符（双引号）",
			command:  `export MSG="hello\"world"`,
			expected: []string{`MSG=hello"world`},
		},
		{
			name:     "单引号内反斜杠不转义",
			command:  `export MSG='hello\"world'`,
			expected: []string{`MSG=hello\"world`},
		},
		{
			name:     "GOPATH 设置",
			command:  "export GOPATH=/root/go",
			expected: []string{"GOPATH=/root/go"},
		},
		{
			name:     "复杂 PATH 设置",
			command:  "export PATH=/usr/local/go/bin:/root/go/bin:$PATH",
			expected: []string{"PATH=/usr/local/go/bin:/root/go/bin:$PATH"},
		},
		// P2: 边界测试
		{
			name:     "空值",
			command:  "export A=",
			expected: []string{"A="},
		},
		{
			name:     "值含等号",
			command:  "export A=foo=bar",
			expected: []string{"A=foo=bar"},
		},
		{
			name:     "未闭合双引号 - 不应添加变量",
			command:  `export A="hello world`,
			expected: nil,
		},
		{
			name:     "未闭合单引号 - 不应添加变量",
			command:  `export A='hello world`,
			expected: nil,
		},
		{
			name:     "非法变量名（数字开头）- 不应添加变量",
			command:  "export 1ABC=val",
			expected: nil,
		},
		{
			name:     "单引号内反斜杠保持原样",
			command:  `export A='hello\nworld'`,
			expected: []string{`A=hello\nworld`},
		},
		{
			name:     "双引号内转义反斜杠",
			command:  `export A="hello\\nworld"`,
			expected: []string{`A=hello\nworld`},
		},
		{
			name:     "未闭合引号后无有效变量",
			command:  `export A=valid B="unclosed`,
			expected: []string{"A=valid"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := parseExportStatements(tt.command)
			if !reflect.DeepEqual(result, tt.expected) {
				t.Errorf("parseExportStatements() = %v, want %v", result, tt.expected)
			}
		})
	}
}

func TestParseEnvFileLines(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		expected map[string]string
	}{
		{
			name: "正常的 export 格式（无引号）",
			content: `# Auto-generated by xbot
export PATH=/usr/local/go/bin:$PATH
export GOPATH=/root/go`,
			expected: map[string]string{
				"PATH":   "/usr/local/go/bin:$PATH",
				"GOPATH": "/root/go",
			},
		},
		{
			name: "单引号包裹的值——正确 unquote",
			content: `export PATH='/usr/local/go/bin:$PATH'
export GOPATH='/root/go'`,
			expected: map[string]string{
				"PATH":   "/usr/local/go/bin:$PATH",
				"GOPATH": "/root/go",
			},
		},
		{
			name:    "含单引号的值——shellEscapeValue 编码后正确还原",
			content: `export MSG='it'\''s a test'`,
			expected: map[string]string{
				"MSG": "it's a test",
			},
		},
		{
			name: "损坏的重复 export 前缀（Bug 1 场景）",
			content: `# Auto-generated by xbot
export export PATH=/usr/local/go/bin
export PATH=/usr/local/go/bin:$HOME/go/bin
export export export GOPATH=/root/go`,
			expected: map[string]string{
				"PATH":   "/usr/local/go/bin:$HOME/go/bin", // 最后一个值覆盖
				"GOPATH": "/root/go",
			},
		},
		{
			name: "空文件和注释",
			content: `# comment
	# another comment

	export FOO=bar`,
			expected: map[string]string{
				"FOO": "bar",
			},
		},
		{
			name:     "空内容",
			content:  "",
			expected: map[string]string{},
		},
		{
			name: "无 export 前缀也兼容",
			content: `PATH=/usr/bin
	GOPATH=/root/go`,
			expected: map[string]string{
				"PATH":   "/usr/bin",
				"GOPATH": "/root/go",
			},
		},
		{
			name: "混合引号和非引号值",
			content: `export A='hello world'
export B=simple
export C='with'\''quotes'`,
			expected: map[string]string{
				"A": "hello world",
				"B": "simple",
				"C": "with'quotes",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := parseEnvFileLines(tt.content)
			if !reflect.DeepEqual(result, tt.expected) {
				t.Errorf("parseEnvFileLines() = %v, want %v", result, tt.expected)
			}
		})
	}
}

func TestShellEscapeUnquoteRoundTrip(t *testing.T) {
	tests := []struct {
		name  string
		value string
	}{
		{"简单值", "hello"},
		{"含冒号和斜杠", "/usr/local/go/bin:/root/go/bin"},
		{"含美元符号", "$PATH:/new/path"},
		{"含单引号", "it's a test"},
		{"含多个单引号", "don't stop believin'"},
		{"空值", ""},
		{"含等号", "foo=bar=baz"},
		{"含特殊shell字符", "$(whoami); rm -rf /"},
		{"含换行——有损转换，检查稳定性", "line1\nline2"},
		{"含反引号", "`uname -a`"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			escaped := shellEscapeValue(tt.value)
			unquoted := shellUnquoteValue(escaped)
			if unquoted != tt.value {
				// newline 是有损转换（\n → 字面 \n），检查稳定性而非完美还原
				if strings.Contains(tt.name, "有损") {
					// 二次 escape+unquote 必须收敛（不再膨胀）
					escaped2 := shellEscapeValue(unquoted)
					unquoted2 := shellUnquoteValue(escaped2)
					if unquoted2 != unquoted {
						t.Errorf("lossy round-trip not stable:\n  first:  %q\n  second: %q", unquoted, unquoted2)
					}
					return
				}
				t.Errorf("round-trip failed:\n  original: %q\n  escaped:  %q\n  unquoted: %q", tt.value, escaped, unquoted)
			}
		})
	}
}

func TestShellUnquoteValue(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{"无引号", "hello", "hello"},
		{"空字符串", "", ""},
		{"单字符", "x", "x"},
		{"普通单引号", "'hello'", "hello"},
		{"含空格", "'hello world'", "hello world"},
		{"含shell转义单引号", "'it'\\''s'", "it's"},
		{"含多个转义单引号", "'don'\\''t stop believin'\\'''", "don't stop believin'"},
		{"双引号不处理", `"hello"`, `"hello"`},
		{"只有开头单引号", "'hello", "'hello"},
		{"只有结尾单引号", "hello'", "hello'"},
		{"PATH值", "'/usr/local/go/bin:$PATH'", "/usr/local/go/bin:$PATH"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := shellUnquoteValue(tt.input)
			if result != tt.expected {
				t.Errorf("shellUnquoteValue(%q) = %q, want %q", tt.input, result, tt.expected)
			}
		})
	}
}
